### ISSUE TITLE
The edge adjacency matrix of undirected graph is not symmetric.

### ISSUE THREAD

**Issue by Lizn-zn** [benedekrozemberczki/MUSAE#2]
In my humble opinion, the matrix corresponding to the undirected graph is symmetric. However, I find it is not the case for the GitHub Social Network(http://snap.stanford.edu/data/github-social.html).  
I try to visualize it as follows.

<img width="596" alt="Screen Shot 2020-09-13 at 19 53 37" src="https://user-images.githubusercontent.com/32972438/93017392-f2103900-f5fa-11ea-95f2-db3a436341b2.png">

**Comment by benedekrozemberczki** [comment]
Can you share the code?

**Comment by benedekrozemberczki** [comment]
Did you call nx adjacency?

**Comment by benedekrozemberczki** [comment]
Could you start the repo and hit a follow?

**Comment by Lizn-zn** [comment]
Originally I wrote a Matlab code to read the adjacency matrix (just load the edge csv). Now I find that I have to call nx adjancy instead of it. But I am very curious why I did not meet this problem on other datasets (e.g. http://snap.stanford.edu/data/ego-Facebook.html)

**Comment by Lizn-zn** [comment]
Thanks for the hint, it should be my fault.
