### ISSUE TITLE
What's the meaning of features?

### ISSUE THREAD

**Issue by Leirunlin** [benedekrozemberczki/MUSAE#3]
I download the datasets (github) from SNAP, but I'm now confused about the features in .json format.
Have they been preprocessed already so that they can be put into use without further processing? 
Or do I need to understand what each dimension in the features mean?

**Comment by benedekrozemberczki** [comment]
It was preprocesses. Features are column indicators of positive binary
values.

**Comment by Leirunlin** [comment]
Thanks for your reply!
So these features can be regarded as node features directly? 
I'm trying to apply GCN to this dataset, and I wonder if more feature engineering might be helpful.

**Comment by benedekrozemberczki** [comment]
The features are described by a binary sparse matrix. Keys are nodes and the values are a list of non-zero columns in the feature matrix. I would recommend the use of some dimensionality reduction on the node feature matrix with sparse TruncatedSVD. We did not open-source the meaning of the features as the data-mining itself was with sensitive data.

**Comment by Leirunlin** [comment]
Thanks!
