### ISSUE TITLE
Node features for Facebook graph

### ISSUE THREAD

**Issue by tsafavi** [benedekrozemberczki/MUSAE#4]
Hi, thanks for your contributions! 

About the Facebook dataset - what do the node features represent, and how were they generated? The paper mentions that the features are extracted from site descriptions. Does this mean they're text features, and if so which text representation or embedding did you use?

**Comment by benedekrozemberczki** [comment]
Dear Tara,

Tags of the page and quantile encodings of doc2vec vectors extracted from
the page descipritons. The fields are free-text populated by the page
owners, because of this a large number of pages had no description.

Bests,

Benedek

**Comment by HAI-syz** [comment]
Hi, thank you for your great work!
I have further questions.

1. FacebookPagePage dataset
    - I want to reduce its dimension from 128 to 64.
    - So can I get the raw text which you used?
    - I saw your recommendation on [issue3](https://github.com/benedekrozemberczki/MUSAE/issues/3). Can I do dimensionality reduction on this dataset, too?

2. Twitch datasets
    - I want to reduce these too.
    - The paper mentions, "Node features are games liked, location and streaming habits."
    - So I think simple dimensionality reduction on this dataset might be harmful.
    - How can I handle these?

Thanks,
