### ISSUE TITLE
A question about node labels

### ISSUE THREAD

**Issue by simon-hope** [benedekrozemberczki/MUSAE#5]
Hi Benedek,

I have one question about the file "DE_target.csv". There are several files like this one in the repository.

There are several columns in this file, including "id", "days", "mature", "view", "partner", and "new_id". I am curious about which column indicates the label of a node, that is, whether a streamer uses explicit language.

Could you give me a hint about this? Many thanks!

Best regards,
Simon

**Comment by benedekrozemberczki** [comment]
Hi there,

It is the mature content one :D.

Bests,

Benedek

**Comment by simon-hope** [comment]
Hi Benedek,

Thanks a lot for such an instantaneous response! :)

Then, in the column named "mature", does the word "False" mean the streamer uses explicit language? 

Please correct me if my understanding is wrong. Thank you!

Best regards,
Simon

**Comment by benedekrozemberczki** [comment]
Mature true essentially means streaming explicit content e.g. webcam porn.

**Comment by simon-hope** [comment]
Dear Benedek,

Got this point with thanks!

Best regards,
Simon
