### ISSUE TITLE
Ask about meaning of node features in Wikipedia datasets

### ISSUE THREAD

**Issue by alexbui91** [benedekrozemberczki/MUSAE#6]
Dear authors,

As Wikipedia is an open site, is it possible to share the mapping ID2Words of these datasets?

Sincerely,
Bests

**Comment by Lukangkang123** [comment]
> Dear authors,
> 
> As Wikipedia is an open site, is it possible to share the mapping ID2Words of these datasets?
> 
> Sincerely, Bests

I have the same problem, do you already have a solution?
